#!/usr/bin/env bash

cd $(dirname $0)/..

IMAGE=fortyseveneffects/avr-builder:latest

docker run --rm -it -v $(pwd):/src -v $(pwd)/build:/build -w /build $IMAGE cmake -DCMAKE_TOOLCHAIN_FILE=/src/builder/platform/avr/toolchain.cmake /src
